### ISSUE TITLE
Fail to install through conda or pip

### ISSUE THREAD

**Issue by bbharland** [deeptime-ml/deeptime#139]
With conda, it hangs trying to solve the environment.  With pip, I get   

`ERROR: Failed building wheel for deeptime
Failed to build deeptime
ERROR: Could not build wheels for deeptime which use PEP 517 and cannot be installed directly`

I assume I can solve this by specifying an older version of wheel?

I completely deleted/reinstalled anaconda and started fresh with a new environment containing:
`name: pytorch-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.5=py38ha65f79e_0
  - future=0.18.2=py38h578d9bd_3
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - liblapack=3.9.0=8_mkl
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - llvm-openmp=11.1.0=h4bd325d_1
  - mkl=2020.4=h726a3e6_304
  - ncurses=6.2=h58526e2_4
  - ninja=1.10.2=h4bd325d_0
  - numpy=1.20.2=py38h9894fe3_0
  - openssl=1.1.1k=h7f98852_0
  - pip=21.1=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - python=3.8.8=hffdb5ce_0_cpython
  - python_abi=3.8=1_cp38
  - pytorch=1.8.0=cpu_py38hd248515_1
  - readline=8.1=h46c0cb4_0
  - setuptools=49.6.0=py38h578d9bd_3
  - sleef=3.5.1=h7f98852_1
  - sqlite=3.35.5=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
prefix: /home/bharland/anaconda3/envs/pytorch-env`

**Comment by clonker** [comment]
Hey, when you are installing it via pip it'll try to compile it locally, you could call `conda install compilers` beforehand. 
conda installation is usually easier. Perhaps give it some more time to sort out the dependencies. If that doesnt work, what is your operating system and the exact commands you invoked and the full error message of the pip install?

Cheers!

**Comment by bbharland** [comment]
Many thanks for your fast reply.  Problem solved!  I had just created the environment, activated it and tried conda install -c conda-forge deeptime and when that didn't work, pip install deeptime.  Then I tried both again in the base environment, and when that failed, conda install in the newly created environment worked.  

I'm pretty sure I wouldn't be able to reproduce this.  Thanks again!

**Comment by clonker** [comment]
Glad it works for you now :) you are welcome
