### ISSUE TITLE
Build fails suddenly

### ISSUE THREAD

**Issue by MQSchleich** [deeptime-ml/deeptime#224]
Hey There!

I was building some stuff recently, when suddenly my CI pipeline failed. According to the report is was because a dependency was not installed properly. 

Please check it here:
[Failed CI](https://github.com/MQSchleich/dylightful/runs/5788471576?check_suite_focus=true)

Do you have any suggestions on what to do?

Thank you!

**Comment by clonker** [comment]
Hey that's definitely a problem on our end. Must be caused by a pip / setuptools update that demands `version` to be specified within pyproject.toml. I'll fix and make a release asap

**Comment by clonker** [comment]
Release is out, could you try again?:)

**Comment by MQSchleich** [comment]
It works now, thank you. :)
