### ISSUE TITLE
Error importing deeptime with scikit-learn 1.2.0

### ISSUE THREAD

**Issue by stefdoerr** [deeptime-ml/deeptime#265]
Any new env with sklearn 1.2.0 will fail with following error
```pytb
  File "/home/sdoerr/Work/deeptime/deeptime/__init__.py", line 4, in <module>
    from . import util
  File "/home/sdoerr/Work/deeptime/deeptime/util/__init__.py", line 101, in <module>
    from .stats import QuantityStatistics, confidence_interval, energy2d, EnergyLandscape2d
  File "/home/sdoerr/Work/deeptime/deeptime/util/stats.py", line 7, in <module>
    from deeptime.util.types import ensure_array
  File "/home/sdoerr/Work/deeptime/deeptime/util/types.py", line 8, in <module>
    from .data import TimeLaggedDataset, TrajectoryDataset, TrajectoriesDataset
  File "/home/sdoerr/Work/deeptime/deeptime/util/data.py", line 8, in <module>
    from ..base import Dataset
  File "/home/sdoerr/Work/deeptime/deeptime/base.py", line 6, in <module>
    from sklearn.base import _pprint as pprint_sklearn
ImportError: cannot import name '_pprint' from 'sklearn.base' (/home/sdoerr/miniconda3/envs/htmd3.10_2/lib/python3.10/site-packages/sklearn/base.py)
```
The function has been converted to a class and been moved to `from sklearn.utils._pprint import _EstimatorPrettyPrinter` but it's used now differently. Might be a good idea to not use hidden functions of external libraries though as they can disappear in new versions.

**Comment by clonker** [comment]
Yeah agree, this is unfortunate and should be avoided. I would also like to avoid pulling another dependency into the library (eyeing at pprint, although it's a very lightweight one). Probably we are fine with a much coarser `__repr__`.

**Comment by stefdoerr** [comment]
I see the release on github but not on anaconda. Do you release them to anaconda at a different schedule?

**Comment by clonker** [comment]
Just took a few hours, release should be on the anaconda cloud now as well
