### ISSUE TITLE
About applying Deeptime to molecular dynamics simulation trajectories on protien

### ISSUE THREAD

**Issue by TianmingQu** [deeptime-ml/deeptime#269]
Dear Deeptime developer,

I have a set of cartesian coordinates from a protein MD simulation. The shape of the coordinates array is (frame_number, atom_number, 3). I would like to use TICA to do decomposition analysis to this array, could you give me some instructions on this?

Best,
Tianming

**Comment by clonker** [comment]
Dear Tianming,

I recommend featurizing your data first. You can of course flatten it (reshape it to `(n_frames, n_atoms * 3)`), this however usually yields poor results in terms of VAMP score. You can think about pairwise distances, VAMPNets, SASA and/or your biochemical intuition to define feature functions. These can be stacked in the second dimension  and fed directly into TICA (or implemented using the observable_transform argument).

Cheers
Moritz

**Comment by TianmingQu** [comment]
> Dear Tianming,
> 
> I recommend featurizing your data first. You can of course flatten it (reshape it to `(n_frames, n_atoms * 3)`), this however usually yields poor results in terms of VAMP score. You can think about pairwise distances, VAMPNets, SASA and/or your biochemical intuition to define feature functions. These can be stacked in the second dimension and fed directly into TICA (or implemented using the observable_transform argument).
> 
> Cheers Moritz

Hi Moritz, 
Thanks a lot for your response. I do tried to use dihedral angles as features, but in that way do you know how I can plot the vectors on VMD? To see how the protein will move along each eigenvector?
Best,
Tianming

**Comment by clonker** [comment]
Hi, sorry I completely forgot to follow up. I am not sure if this is possible in VMD at all. What you can do is draw representative structures of metastable states and along the transition from your trajectories based on the state assignment in the clustering. That should give you an idea of what the motion that is described by the eigenfunctions looks like.
