### ISSUE TITLE
Handling parallel simulations

### ISSUE THREAD

**Issue by SianXiaoCHN** [deeptime-ml/deeptime#270]
Hi,

Do we have the feature for the situation we have parallel runs for simulations, and we want to use them all for the dimension reduction/clustering/MSM. I tried to concatenate them by index (axis=0), it works fine (maybe? The lag time should be a problem for the connecting points right?). I tried to put the trajectories into a list, TICA gives unreasonable results.

**Comment by clonker** [comment]
Hi @SianXiaoCHN, if you can fit your data into memory (ie direct `fit`, no `partial_fit`), you'll want (as a data layout) something like this:

```
trajectories = [ traj1, traj2, traj3, ... ]
```

which each `trajN` being a `(T, d)`-shaped numpy array. In case of partial fit it is always a (section of) one `trajN. Never mix frames between two trajectories into the same numpy array in either case. Keep in mind that your trajectories have to be at least `lagtime` long.

You may also try to use the `TrajectoriesDataset.from_numpy`, documented [here](https://deeptime-ml.github.io/latest/api/generated/deeptime.util.data.TrajectoriesDataset.html).

It is no problem that these are parallel simulations. :)
