### ISSUE TITLE
Does one need identical features to compare between related systems?

### ISSUE THREAD

**Issue by cgseitz** [deeptime-ml/deeptime#285]
Hello,

I have two related systems, system A and system B. In their MD trajectories, they show somewhat different conformational states - system A reaches one state, and system B reaches that same state and then goes a bit further. I am trying to use MSMs to quantify the kinetic differences between these two systems. So far, I have used identical features across both systems with the goal of directly comparing the kinetics differences. However, I am finding a hard time creating features that work well for both systems - either system A or system B responds well to the features I choose, but not both. By this, I mean that one system will show its conformational change with a reasonable MFPT, and the other will have an extremely long MFPT (in the tens of seconds range for trajectories that total 500 ns). I know that these extremely long MFPTs are biologically unreasonable because with a different set of features I can capture the exact same conformational change but with significantly shorter MFPTs. Since only the MFPTs change while the conformational transitions stay the same, I have a good idea of a reasonable MFPT and the conformational change. Can I create separate sets of features that capture reasonable MFPTs and conformational changes in each of my systems, or do these features need to stay the same to retain validity when comparing the two? Any thoughts, suggestions or advice you have would be much appreciated. Thanks!

Best,
Christian

**Comment by clonker** [comment]
Hi Christian,

sorry for the long delay. Generally I would say that things like MFPT (i.e., quantities related to the process itself and not the operator /-approximation) should remain valid independent of the feature set you have chosen. That being said you'll of course have different error margins on either of them. I would probably try to optimize them independently and get some error margins with Bayesian sampling. I don't think it is easily possible to compare the operators though. To that end you could try to estimate one operator jointly on both datasets but then again - as you have rightfully noted - it is hard to get features which work well in two different systems. Which also speaks to: it's a different process, different operator, therefore different singular functions that describe the dynamics.
Not sure if that is of any help, but yeah. I think independent optimization and trying to get error margins on quantities which are not directly related to the operator (like VAMP score would not work).

Cheers, Moritz.

**Comment by clonker** [comment]
Hi, by operators I mean (mainly) Koopman operators which reflect the propagation of observables in the underlying dynamics through time in dynamical systems . You can understand a bunch of different methods (TICA, VAMP, MSMs, VAMPNets, KCCA, eDMD, i'm sure I am missing some) as approximations to the true underlying operator. In the end MFPTs and stationary distributions are derived from these approximations but in turn they model an emergent property of the real process, which makes it quantifiable and comparable. The VAMP score on the other hand quantifies how well you managed to approximate the operator in the first place in the sense of a variational principle. In that sense it's more a property of the operator (approximation) and less a property of the process. If the mathematics of it all is something that interests you, you can have a look at the deeptime paper. There I tried to set most of the implemented methods into context with each other and introduce the concepts - probably better than I could do it in a github issue :-D.

Cheers, Moritz

**Comment by cgseitz** [comment]
Hi Moritz,

Thanks so much. I will check that paper out to investigate further, but this seems straightforward to me.

Best,
Christian
