### ISSUE TITLE
Applying TICA to ragged feature vectors 

### ISSUE THREAD

**Issue by ryankzhu** [deeptime-ml/deeptime#289]
Hi, I am doing tica transformation on some featurised md trajectories of different lengths `List[np.ndarray] of shape (x, 15) where x differs`. I got the following error: 

```
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1983,) + inhomogeneous part.
```

I guess it's because I am having a ragged list of arrays that can't be converted to a single array. Is there a away to directly apply tica to such feature vectors?

**Comment by clonker** [comment]
Not directly, no; the data has to live in some vector space. If you can formulate it that way then tica should be (at least technically) applicable

**Comment by ryankzhu** [comment]
Okay thank you very much for the suggestion!
