### ISSUE TITLE
Regarding trajectory data

### ISSUE THREAD

**Issue by GSINGH006** [deeptime-ml/deeptime#297]
Hi, I was going through DeepTime documentation, Like in pyEmma  I could source my data instead of loading and using the source object for TICA, but I couldn't use the same source object for TICA in Deeptime. Is there any way around it where I can source my data instead of loading it?
 Thank you

**Comment by clonker** [comment]
Admittedly, the data api of pyemma is more fleshed out than deeptime's and I always wanted to change that, never got around to it, though. You can still use the pyemma `source` api and combine it with deeptime by using `partial_fit`.

**Comment by GSINGH006** [comment]
Hi @clonker ,I have looked into it and I am using the following code for the same:
topfile = "/home/lab/Downloads/penta_traj/pentapeptide-impl-solv.pdb"
traj_list=["/home/lab/Downloads/penta_traj/pentapeptide-00-500ns-impl-solv.xtc","/home/lab/Downloads/penta_traj/pentapeptide-01-500ns-impl-solv.xtc"]
import pyemma
import deeptime as dt
import numpy as np
import matplotlib.pyplot as plt
import mdshare
plt.matplotlib.rcParams.update({'font.size': 16})
import numpy as np
feat= pyemma.coordinates.featurizer(topfile)
tor=feat.add_backbone_torsions(cossin=True)
**y= pyemma.coordinates.source(traj_list, feat)
data=y.get_output()**
a=np.array(data)
from deeptime.decomposition import TICA
tica_estimator = TICA(lagtime=1,dim=2)
tica = tica_estimator.partial_fit(a)
par_tic=tica.fetch_model()
tics=par_tic.transform(a)
Is this the way to use the partial_fit method?I am using 25 independent trajectories.
Thank you.
