### ISSUE TITLE
The link in the README is broken

### ISSUE THREAD

**Issue by pl992** [deeptime-ml/deeptime#91]
This link in the README is broken: https://scikit-time.github.io/

I would like to check the documentation but I don't know where else to find it

**Comment by clonker** [comment]
Sorry for that, I am currently implementing a name-change from `scikit-time` to `deeptime`. You can find the documentation under `deeptime-ml.github.io`. If you want to install the package I recommend waiting for another half an hour, then the name-change is going to be completed. I will add another comment to this issue to let you know.

**Comment by clonker** [comment]
Fixed and available.
