### ISSUE TITLE
How to pass arguments in the method gather_stats of deeptime.markov.hmm.BayesianHMMPosterior

### ISSUE THREAD

**Issue by pl992** [deeptime-ml/deeptime#92]
After I evaluated the `deeptime.markov.hmm.BayesianHMMPosterior` as:
```
hmm = HMM.MaximumLikelihoodHMM(initial_model=HMM.init.discrete.metastable_from_data(data,3,2000)).fit(data).fetch_model()
bayesian_hmm = HMM.BayesianHMM(initial_hmm=hmm).fit(data).fetch_model()
```
I would like to evaluate the average and the standard deviation of the mfpt of the transition_model but I couldn't find a way of inserting the arguments:
`stats = bayesian_hmm.gather_stats('transition_model/mfpt')`
I would like to use the metastable state 0,1 or others but I couldn't figure out how to pass these arguments to mfpt (in the documentation it is written you are able to)

**Comment by clonker** [comment]
It should be just

```python
stats = bayesiam_hmm.gather_stats('transition_model/mfpt', A=[0], B=[1])
```
